NAME=main
VIEWPDF=evince
BIBTEXSRCS=main.bib
USE_PDFLATEX=1
CLEAN_FILES+=*.synctex.gz main.fdb_latexmk main.tar.gz *.bak *.tmp *.fls *.run.xml *.fdb_latexmk *.bcf
EXTRA_DIST+=*.pdf iop* 

include /usr/share/latex-mk/latex.gmk
